### ISSUE TITLE
how to install "en_US.UTF-8"

### ISSUE THREAD

**Issue by kakabuluo** [openSUSE/docker-containers-build#12]
Hi,
      When I run command "locale -a", I found that there has no "en_US.UTF-8"
```
bash-4.2# locale -a  
C  
POSIX  
bash-4.2#  
```
so, how to install it?
Thanks for you time

**Comment by flavio** [comment]
We deliberately remove all the unnecessary locales to save disk space. You can have all of them back by doing:

```
zypper -n in -f glibc-locale
```

There's no way to selectively install just one locale
