### ISSUE TITLE
some binaries are outdated

### ISSUE THREAD

**Issue by dbloms** [openSUSE/docker-containers-build#13]
Hi,

it seems that the images is outdated, it would be nice to have an updated image:

~> docker images opensuse:leap
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
opensuse            leap                7617deda9fe6        6 weeks ago         97.67 MB

~> docker run -ti opensuse:leap  bash
bash-4.2# zypper lu
Retrieving repository 'NON-OSS' metadata ......................................................................................[done]
Building repository 'NON-OSS' cache ...........................................................................................[done]
Retrieving repository 'OSS' metadata ..........................................................................................[done]
Building repository 'OSS' cache ...............................................................................................[done]
Retrieving repository 'OSS Update' metadata ...................................................................................[done]
Building repository 'OSS Update' cache ........................................................................................[done]
Retrieving repository 'Update Non-Oss' metadata ...............................................................................[done]
Building repository 'Update Non-Oss' cache ....................................................................................[done]
Loading repository data...
Reading installed packages...
S | Repository | Name              | Current Version | Available Version | Arch  
--+------------+-------------------+-----------------+-------------------+-------
v | OSS Update | insserv-compat    | 0.1-13.4        | 0.1-15.1          | noarch
v | OSS Update | libcap2           | 2.22-14.4       | 2.22-16.1         | x86_64
v | OSS Update | libgcrypt20       | 1.6.1-20.1      | 1.6.1-23.1        | x86_64
v | OSS Update | libsolv-tools     | 0.6.18-3.1      | 0.6.19-6.1        | x86_64
v | OSS Update | libssh2-1         | 1.4.3-10.1      | 1.4.3-12.1        | x86_64
v | OSS Update | libudev1          | 210-86.1        | 210-89.1          | x86_64
v | OSS Update | libzypp           | 15.21.1-3.2     | 15.21.4-6.1       | x86_64
v | OSS Update | suse-module-tools | 12.3-16.1       | 12.3-18.1         | x86_64
v | OSS Update | systemd           | 210-86.1        | 210-89.1          | x86_64
v | OSS Update | zypper            | 1.12.31-3.1     | 1.12.37-6.1       | x86_64
bash-4.2#

**Comment by flavio** [comment]
The image inside of the official namespace is outdated because of this issue https://github.com/docker-library/official-images/pull/1537#issuecomment-196652045

There's nothing we can do, it's a problem on the docker hub.

In the meantime you can get latest images with `docker pull opensuse/amd64:leap`
