### ISSUE TITLE
Add Leap 42.2 image

### ISSUE THREAD

**Issue by afaerber** [openSUSE/docker-containers-build#15]
With Beta 1 of Leap 42.2 out, can you set up an openSUSE-42.2 branch and corresponding [Kiwi build](https://build.opensuse.org/project/subprojects/Virtualization:containers:images) please?

**Comment by afaerber** [comment]
https://github.com/openSUSE/docker-containers/pull/17 already merged the templates.

**Comment by lnussel** [comment]
@flavio ?

**Comment by tboerger** [comment]
We still want to provide Jenkins jobs that automatically updates the branches

**Comment by tboerger** [comment]
Beside that we need to provide the content for https://build.opensuse.org/package/show/Virtualization:containers:images:openSUSE-42.2/openSUSE-42.2-docker-image

**Comment by tboerger** [comment]
I have accepted https://build.opensuse.org/request/show/428993 now to get it built on OBS.

**Comment by tboerger** [comment]
@flavio please push the branch when the build is done, than we can close this issue.

**Comment by tboerger** [comment]
Now we got https://github.com/openSUSE/docker-containers-build/tree/openSUSE-42.2 and also `opensuse/amd64:42.2` so I will close this issue for now.

**Comment by tkelman** [comment]
Sorry to post on a long-closed issue, but does anyone have a good handle on why the 42.2 image is 38.5% larger than the 42.1 image? And tumbleweed is 61% larger than 42.1?

**Comment by flavio** [comment]
I think @schaefi might have looked into that sometimes ago... @schaefi, do you recall your findings?

**Comment by schaefi** [comment]
All the information I found I put on the trello card of the docker team. I'm afraid I can't remember the card name. If nothing has changed in the list of packages for the container setup between 42.1, 42.2 and TW the only reason for the huge size difference is due to changed package requirements.

It would help if we can run:

```bash
kiwi-ng image info --description path/to/image/description --resolve-package-list
```

and compare the results with a diff check
