### ISSUE TITLE
Publish images to library

### ISSUE THREAD

**Issue by tboerger** [openSUSE/docker-containers-build#16]
We need to update the official library, especially since we got https://github.com/openSUSE/docker-containers-build/tree/openSUSE-42.2 now.

**Comment by flavio** [comment]
I don't think we should update the image inside of the official library to use 42.2 given it's not out there yet.

I'm fine with updating the existing 42.1 image to a more recent one. In that case please submit the image and add me to the PR against library.

**Comment by tianon** [comment]
I've included `library/opensuse` in https://github.com/docker-library/official-images/pull/2254, but I'm happy to remove the update there if you'd prefer to update this yourselves. :smile: :+1:

**Comment by tboerger** [comment]
@tianon thanks, totally fine with that change. So let's close this issue.
