### ISSUE TITLE
Document how to start services

### ISSUE THREAD

**Issue by gallardo** [openSUSE/docker-containers-build#17]
I pulled [opensuse:42.1](https://github.com/openSUSE/docker-containers-build/blob/c8abb4323ef1744bfb9e5d4f127d9076083f0a6e/docker/Dockerfile), installed mysql  (`zypper in mysql`) and naively tried to start it as a service (first, assuming systemd, with `systemctl start mysql`; and after a `Failed to get D-Bus connection: Unknown error -1` and resourcing to reading the package doc, with a non-existing `rcmysql start`).

I guess I'm missing something pretty obvious, but I cannot find what. I've tried with several options proposed for other images and configurations, but these doesn't help either (`--privileged`, `--cap-add SYS_ADMIN -v /sys/fs/cgroup:/sys/fs/cgroup:ro`).

Could you document how services are supposed to be started? (In other words, how should we start the container?)

I'm using

    docker --version
    Docker version 1.11.0, build 4dc5990

**Comment by tboerger** [comment]
It's pretty uncommon to use anything like that in containers. The common use case is to launch a single service directly, without systemd or sysvinit. If you still got questions feel free to ask, I will close this issue for now.

**Comment by gallardo** [comment]
@tboerger My plan was to test a webapp, so I though:

1. `docker run -ti -name myapp ... opensuse:42.1 ...`
2. (In myapp) `zypper in tomcat`
3. Edit `/etc/default/tomcat`
4. Start tomcat (`rctomcat`, `/etc/init.d/tomcat`, `systemctl start tomcat`)

In this case I could as well install tomcat and exec `catalina start`, but first I have to make sure that running tomcat this way is equivalent to running it in our production. All in all, I wanted to test something I can easily replicate in our production environment (no docker in production).

**Comment by gallardo** [comment]
Update from [alcohol](https://botbot.me/freenode/docker-library/msg/75510569/):

> [17:29] \<alcohol\> Guest38249: the containter should just directly run tomcat
> [...]
> [10:11] \<alcohol\> Guest38249: in short, it's very much about process isolation
> [10:12] \<alcohol\> Guest38249: running two processes in one container does not really constitute isolation anymore..

and [Geo](https://botbot.me/freenode/docker-library/msg/75511838/):

> 17:29] \<Geo\> Your executable binary is tomcat itself, so in essence the container *is* tomcat (or whatnot)
> [17:30] \<Geo\> if the container is running, tomcat is running. If tomcat dies, so does the container
> [...]
> [17:57] \<Geo\> and I guess you could argue that at this point, whats easier- two containers, or trying to get it to do something it wasnt designed to do :)

Looks as if I had missed Docker's goal...
