### ISSUE TITLE
Mandatory files in /etc/ not shipped with docker container

### ISSUE THREAD

**Issue by dothebart** [openSUSE/docker-containers-build#18]
I've run:
`docker run -it --volume /tmp/:/build opensuse:13.1  /bin/bash`

And I'd expect these files to be there:

    /etc/os-release
    /etc/rc.status

but they're missing.
similar centos containers do ship it. 
Building rpms would lean on the presence of the first, starting deamons via init scripts on the presence of the second.

**Comment by tboerger** [comment]
13.1 doesn't provide this file, only SuSE-release, beside that 13.1 reached Eola.

**Comment by dothebart** [comment]
while `os-release` is there in 13.2, `rc.status` isn't. so I think this is still a bug that should be fixed.

**Comment by tboerger** [comment]
os-release have been first introduced in 13.2, not before.

**Comment by dothebart** [comment]
yes, but, again, what about `rc.status` ?

**Comment by tboerger** [comment]
Why should that be part of a container? The containers don't provide an init system.
