### ISSUE TITLE
Login shells do not source /etc/profile.local or /etc/profile.d/*

### ISSUE THREAD

**Issue by MihaiB** [openSUSE/docker-containers-build#20]
Dockerfile to reproduce:
```Dockerfile
FROM opensuse:tumbleweed
RUN echo 'echo hello from /etc/profile' >>/etc/profile \
 && echo 'echo hello from /etc/profile.local' >>/etc/profile.local \
 && echo 'echo hello from /etc/profile.d/hello.sh' >/etc/profile.d/hello.sh
RUN su --login
```
Running `docker build --no-cache --force-rm .` I expect to see all `hello` messages. Instead, it prints only:
```
hello from /etc/profile
```
I believe this started happening around 1 week ago when the `opensuse` docker image was updated.

If I add the `echo` commands to the same files in OpenSUSE Tumbleweed installed on my computer, `su --login` prints all the `hello` messages. My OS is up to date, but I have not tried doing a fresh install to check the behavior.

**Comment by tboerger** [comment]
How do you launch the container?

**Comment by MihaiB** [comment]
I didn't launch a container, just:
```
docker build --no-cache -t myimg .
```
and checking the output of the last `RUN` command from the Dockerfile.

Any way I can think to launch a container that starts a login shell, e.g.:
```
docker run --rm myimg bash --login
```
gives the same output. Only:
```
hello from /etc/profile
```
but not the `hello` messages from `/etc/profile.local` or `/etc/profile.d/hello.sh`.

**Comment by tboerger** [comment]
docker run -ti --rm myimg bash

**Comment by MihaiB** [comment]
Same behavior. Of course `-ti` lets me use the shell, but the issue is that `/etc/profile.local` and `/etc/profile.d/*` are not sourced by the login shell.

According to [these OpenSUSE Leap docs](https://doc.opensuse.org/documentation/leap/startup/single-html/book.opensuse.startup/index.html#sec.adm.whatistheshell), a login shell should source the files I mentioned.

Instead, both `opensuse:leap` and `opensuse:tumbleweed`show the behavior I reported: they only source `/etc/profile`.

**Comment by flavio** [comment]
I suspect this might be happening because we deliberately removed some unneeded packages to keep the images as small as possible.

What is your use case, what are you trying to achieve?

**Comment by MihaiB** [comment]
I'm trying to set the locale to English US UTF-8. I managed to do it by installing `glibc-locale` and setting an env var in `/etc/profile.d/my-locale.sh`. After that, login shells (`su --login`, `bash --login`) have the desired locale.

My method stopped working recently, so I worked around it by using `/etc/profile` instead of `/etc/profile.d/*` and opened this issue in case this was a bug that should be fixed.

Now that you pointed it out, indeed after installing a long list of packages in Docker ([these](https://github.com/MihaiB/src/blob/a3c266c781882db20206a10c5d3c21cb38716467/setup/linux-pkgs/add-suse) and a few others) all the `profile*` files get sourced by login shells. So the functionality is likely provided by some package not part of the base image 👍.

It looks like this wasn't a bug after all, so to keep this issue on topic please close it if there is nothing else left.

***

Should I open another issue asking for the recommended way to set the `en_US.UTF-8` locale? Do enough users run into this problem? If search engines link to it, the issue might be useful. The existing issues discuss installing `glibc-locale` but not how to change the system locale.
But I realize this might be outside the scope of the containers team.
For example, simply doing `print('✓')` from a Python3 script produces `UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 0: ordinal not in range(128)`. And there might be other programs or use cases that require a UTF-8 locale.

With just a tiny example I can show the problem and a working solution, aiming to have it improved (or at least reviewed) by someone knowledgeable on the topic.

**Comment by tboerger** [comment]
As I'm on mobile I can't tell you where this tool comes from, but the proper way to set a system locale should be:

localectl set-locale LANG=

But beside that our kiwi definition for the base image can also define a locale.

**Comment by tboerger** [comment]
For reference: https://github.com/openSUSE/docker-containers/blob/master/openSUSE-Tumbleweed/config.kiwi#L21

**Comment by MihaiB** [comment]
Thank you for the quick responses.

`cnf localectl` points to `systemd`. But in a container:
```
$ zypper --non-interactive install systemd
$ localectl
Failed to create bus connection: No such file or directory
```
I guess it requires systemd to be running, and after a quick websearch this seems non-trivial.
I will close this issue since the original reason for which I opened it is resolved.
