### ISSUE TITLE
Tags for current major versions

### ISSUE THREAD

**Issue by livelace** [openSUSE/docker-containers-build#21]
Is there a possibility to add a feature that allows pull the current major images ?  

For instance:

docker pull debian:7 -> will download debian:7.17 image version

docker pull opensuse:13 -> will download 13.2 (or 13.3, if 13.3 - it's the latest release)

**Comment by tboerger** [comment]
I don't think that we will provide that as these versions are not really comparable to the versions of Debian and so on. Beside that, the 13.x versions are nearby EOL

**Comment by livelace** [comment]
What ? This is a simple step - tag your latest version (13.3, 42.2, 54.4) with major version (13, 42, 54). People don't need to know which version is latest in 13, 42, 54 releases.

PS. >_<

**Comment by tboerger** [comment]
No, it's not like that. I would compare the opensuse minor versions more with Debian major versions. Between the versions are major changes, so there can be incompatibilities that will result in broken setups. So I'm sure that the current tagging will stay like that.

**Comment by livelace** [comment]
Forget about Debian or Ubuntu. Answer to a simple question. How people can know which the latest release of the specific version ? How people can download the latest release without knowledge about the latest version ?

PS. Again - forget about differences between distros.

**Comment by tboerger** [comment]
@flavio maybe this is something you can better explain or give a decision as the containers lead.

**Comment by flavio** [comment]
Sorry for the long delay...

@livelace this has been fixed in the meantime. We are tagging our releases as 13.1, 13,2, 42.1, 42.2,... You can see that [here](https://hub.docker.com/r/library/opensuse/tags/) and [here](https://hub.docker.com/r/opensuse/amd64/tags/).

**Comment by tboerger** [comment]
@flavio he was talking about tagging `:13` and `:42`
