### ISSUE TITLE
Not able to install packages in openSuse docker image

### ISSUE THREAD

**Issue by rohitsakala** [openSUSE/docker-containers-build#31]
I had pulled the latest docker image 
```https://hub.docker.com/r/s390x/opensuse/``` to run on Z
and was trying to install packages using the command 
```zypper -n in ruby-devel libmysqld-devel sqlite3-devel postgresql-devel libxslt-devel libxml2-devel libxml2 python3-kiwi wget sudo gcc-c++ curl git kpartx dracut libopenssl-devel which```

But I am getting the following error 

![opensuseerror](https://user-images.githubusercontent.com/8402361/40057652-8443e774-586c-11e8-80a6-12f5f1f002e8.png)

**Comment by flavio** [comment]
Are you sure the image has repositories configured? (`zypper lr -u`)

**Comment by flavio** [comment]
Also... I wonder if this actually an image made by openSUSE. ping @davidcassany, @vogtinator

**Comment by rohitsakala** [comment]
Hi @flavio ,

The command ``` zypper lr -u``` gives me this output.

![lru](https://user-images.githubusercontent.com/8402361/40067569-0f106564-5884-11e8-8a95-efa38da658f7.png)

Also, I found two docker hub repo for s390x OpenSuse Image. Which one should I use ?
1. https://hub.docker.com/r/opensuse/s390x/
2. https://hub.docker.com/r/s390x/opensuse/

Thanks :)

**Comment by flavio** [comment]
These repositories do not contain packages for s390. If you open them from your browser you will see there are no s390 binaries.

To be honest I don't think openSUSE publishes s390x packages... @sysrich: do you know something about that?

**Comment by Vogtinator** [comment]
We have openSUSE Tumbleweed for zSystems. openQA hasn't passed for quite a while though so the packages are quite outdated.

The only official openSUSE Tumbleweed container for s390x is available at `opensuse/tumbleweed`.

The repository to use is http://download.opensuse.org/ports/zsystems/tumbleweed/repo/oss/ BTW.

**Comment by rohitsakala** [comment]
Hi @Vogtinator @flavio ,

Thank you for pointing me to the right docker image and the right repository. I am facing few problems installing the packages such as the following one. Whom should I contact for these kind of errors ? or Please point me out to any slack/irc/forum link you know of ?

![errorpackage](https://user-images.githubusercontent.com/8402361/40109998-8881da70-591c-11e8-8dfd-6a837dcbe4cf.png)

**Comment by Vogtinator** [comment]
> Whom should I contact for these kind of errors ? or Please point me out to any slack/irc/forum link you know of ?

There is a mailing list: https://lists.opensuse.org/opensuse-zsystems/
You can also ask in #opensuse-factory on freenode.

The container is more recent than the latest released packages, as zSystems hasn't passed QA for quite a while, as I mentioned.

This happens because the port for zSystems is decoupled from the TW releases for x86, except for the container. This had to be that way as otherwise we wouldn't have a container release at all...

As a workaround you can select the "downgrade" option when you get asked. Alternatively, I could probably change the container to build against the last released zSystems snapshot (mid 2017...)

**Comment by rohitsakala** [comment]
Thank you for the solution. I will try around with the downgrade option. But I will also like to have access to the container based on mid 2017. Could you please provide me to the docker container link of mid 2017 ? 
Thank you once again.

**Comment by Vogtinator** [comment]
> Thank you for the solution. I will try around with the downgrade option. But I will also like to have access to the container based on mid 2017. Could you please provide me to the docker container link of mid 2017 ?
Thank you once again.

I checked - unfortunately I can't, the mid 2017 packages are not on OBS anymore.

I could build such a container locally, but that would not be official anymore.

This is a rather hacky Dockerfile which downgrades the container to the mid-2017 state.
No guarantee that it works as expected, but I don't expect any major problems (other than using mid-2017 packages...)

```
FROM opensuse/tumbleweed
RUN zypper --non-interactive in --oldpackage product:openSUSE-20170505-0.s390x
RUN zypper --non-interactive in --force rpm zypper libsolv-tools libzypp libpopt0
RUN cp /usr/lib64/liblua5.3.so.5.3.0 .
RUN rpm -e --nodeps liblua5_3-5
RUN cp liblua5.3.so.5.3.0 /usr/lib64/liblua5.3.so.5
RUN cp liblua5.3.so.5.3.0 /usr/lib64/liblua.so.5.3
RUN zypper --non-interactive in liblua5_3
RUN zypper --non-interactive dup --download as-needed
RUN rm liblua5.3.so.5.3.0
```

**Comment by rohitsakala** [comment]
Thank you for the workaround. For now, it works with the hack. I will close the issue.

**Comment by rohitsakala** [comment]
Hi @Vogtinator ,

The repo http://download.opensuse.org/ports/zsystems/tumbleweed/repo/oss/ doesn't have packages for runit, xen-libs, xen-tools-domU. Whom should I contact for the addition of these packages?

**Comment by Vogtinator** [comment]
The [opensuse-factory] mailing list: https://lists.opensuse.org/opensuse-factory/
