### ISSUE TITLE
Container init

### ISSUE THREAD

**Issue by brunowego** [openSUSE/docker-containers-build#32]
I am trying start a container with `SYS_ADMIN` compatibilities.

```sh
docker run --cap-add SYS_ADMIN -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d --name opensuse opensuse:42.3 /sbin/init
```

The init binary not exists, have an alternative way? Thanks!

**Comment by davidcassany** [comment]
openSUSE base images do not include systemd, thus there is no init. Docker images are not supposed to run systemd, but if you still want the `/sbin/init` for some reason it is as simple as installing `systemd` in a dervied image.

**Comment by brunowego** [comment]
Thanks @davidcassany 👍
