### ISSUE TITLE
locale, glibc-locale issues

### ISSUE THREAD

**Issue by imbroglioj** [openSUSE/docker-containers-build#6]
Container image Version: openSUSE 20150725 (Tumbleweed) (x86_64)
Docker version 1.6.2, build 7c8fca2; running on ubuntu 14.04.2
After running into locale issues with a (tar) copy of mongodb, I tried installing mongodb with zypper. I got this error:
"Retrieving package glibc-locale-2.22-2.2.x86_64                       (1/3),   6.0 MiB (115.3 MiB unpacked)
Media source 'http://download.opensuse.org/factory/repo/oss/' does not contain the desired medium"

I tried "zypper install glibc-locale" and got the same error.
Note: I am new to Suse, so I wouldn't know whether this issue is docker-image specific
Thanks -- JB

**Comment by flavio** [comment]
You have to refresh repositories' metadata:

```
sudo zypper ref
```

**Comment by imbroglioj** [comment]
Thank you very much. I missed that command.  
Also, I was able to resolve the locale problem I had had on the suse 13.2 version. So all good now. -JB
